"""Tau coding-agent application package."""

from tau_coding.commands import (
    CommandRegistry,
    CommandResult,
    SlashCommand,
    create_default_command_registry,
)
from tau_coding.context import (
    discover_project_context,
    discover_project_context_with_diagnostics,
)
from tau_coding.context_window import (
    estimate_context_tokens,
    estimate_message_tokens,
    estimate_text_tokens,
    estimate_tool_tokens,
    summarize_messages_for_compaction,
)
from tau_coding.credentials import CredentialStoreError, FileCredentialStore, credentials_path
from tau_coding.paths import TauPaths
from tau_coding.prompt_templates import (
    PromptTemplate,
    load_prompt_templates,
    load_prompt_templates_with_diagnostics,
    render_prompt_template,
)
from tau_coding.provider_catalog import (
    BUILTIN_PROVIDER_CATALOG,
    ProviderCatalogEntry,
    builtin_provider_entry,
)
from tau_coding.provider_config import (
    DEFAULT_MODEL,
    DEFAULT_PROVIDER_NAME,
    AnthropicProviderConfig,
    OpenAICompatibleProviderConfig,
    ProviderConfig,
    ProviderConfigError,
    ProviderSelection,
    ProviderSettings,
    anthropic_config_from_provider,
    builtin_provider_configs,
    default_openai_provider_config,
    load_provider_settings,
    openai_compatible_config_from_provider,
    provider_config_from_catalog_entry,
    provider_kind,
    provider_settings_path,
    resolve_provider_selection,
    save_provider_settings,
    upsert_openai_compatible_provider,
    upsert_provider,
)
from tau_coding.rendering import (
    EventRenderer,
    FinalTextRenderer,
    JsonEventRenderer,
    PrintOutputMode,
    TranscriptRenderer,
    create_event_renderer,
)
from tau_coding.resources import ResourceDiagnostic, ResourceError, TauResourcePaths
from tau_coding.session import (
    CodingSession,
    CodingSessionConfig,
    ModelChoice,
    default_session_path,
    jsonl_session_storage,
)
from tau_coding.session_manager import CodingSessionRecord, SessionManager
from tau_coding.skills import (
    Skill,
    build_skill_index,
    expand_skill_command,
    load_skills,
    load_skills_with_diagnostics,
)
from tau_coding.system_prompt import (
    BuildSystemPromptOptions,
    ProjectContextFile,
    build_system_prompt,
    collect_prompt_guidelines,
    format_available_tools,
    format_guidelines,
    format_project_context,
    format_skills_for_prompt,
)
from tau_coding.tools import (
    ToolDefinition,
    create_bash_tool,
    create_bash_tool_definition,
    create_coding_tools,
    create_edit_tool,
    create_edit_tool_definition,
    create_read_tool,
    create_read_tool_definition,
    create_write_tool,
    create_write_tool_definition,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "CodingSession",
    "CodingSessionConfig",
    "CodingSessionRecord",
    "CommandRegistry",
    "CommandResult",
    "DEFAULT_MODEL",
    "DEFAULT_PROVIDER_NAME",
    "BuildSystemPromptOptions",
    "BUILTIN_PROVIDER_CATALOG",
    "EventRenderer",
    "FinalTextRenderer",
    "JsonEventRenderer",
    "ModelChoice",
    "AnthropicProviderConfig",
    "OpenAICompatibleProviderConfig",
    "PrintOutputMode",
    "ProjectContextFile",
    "PromptTemplate",
    "ProviderCatalogEntry",
    "ProviderConfig",
    "ProviderConfigError",
    "ProviderSelection",
    "ProviderSettings",
    "ResourceDiagnostic",
    "ResourceError",
    "SessionManager",
    "Skill",
    "SlashCommand",
    "TauPaths",
    "TauResourcePaths",
    "ToolDefinition",
    "TranscriptRenderer",
    "anthropic_config_from_provider",
    "build_skill_index",
    "build_system_prompt",
    "builtin_provider_configs",
    "builtin_provider_entry",
    "collect_prompt_guidelines",
    "CredentialStoreError",
    "create_bash_tool",
    "create_bash_tool_definition",
    "create_coding_tools",
    "create_edit_tool",
    "create_edit_tool_definition",
    "create_default_command_registry",
    "create_event_renderer",
    "create_read_tool",
    "create_read_tool_definition",
    "create_write_tool",
    "create_write_tool_definition",
    "credentials_path",
    "default_session_path",
    "default_openai_provider_config",
    "discover_project_context",
    "discover_project_context_with_diagnostics",
    "estimate_context_tokens",
    "estimate_message_tokens",
    "estimate_text_tokens",
    "estimate_tool_tokens",
    "summarize_messages_for_compaction",
    "expand_skill_command",
    "format_available_tools",
    "format_guidelines",
    "format_project_context",
    "format_skills_for_prompt",
    "FileCredentialStore",
    "jsonl_session_storage",
    "load_provider_settings",
    "load_prompt_templates",
    "load_prompt_templates_with_diagnostics",
    "load_skills",
    "load_skills_with_diagnostics",
    "openai_compatible_config_from_provider",
    "provider_config_from_catalog_entry",
    "provider_kind",
    "provider_settings_path",
    "render_prompt_template",
    "resolve_provider_selection",
    "save_provider_settings",
    "upsert_provider",
    "upsert_openai_compatible_provider",
]
